name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Install GoogleTest dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake

    - name: Run GoogleTest suite
      run: make test
